FROM node:22
# MAINTAINER Dennis Wolters <mail@dwolt.de>
ENV DEBIAN_FRONTEND noninteractive
ENV DEBIAN_PRIORITY critical
ENV DEBCONF_NOWARNINGS yes
ARG PANDOC_VERSION=3.7
ENV PANDOC_VERSION=${PANDOC_VERSION}
ENV NODE_ENV production
RUN apt-get -qq update && \
    apt-get -qq -y install wget texlive-latex-base texlive-fonts-recommended && \
    apt-get -qq -y install texlive-fonts-extra texlive-latex-extra && \
    apt-get clean

RUN wget https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb && \
    dpkg -i pandoc* && \
    rm pandoc* && \
    apt-get clean

RUN mkdir /app
WORKDIR /app
COPY ./ /app
RUN npm install
ARG PANDOC_PORT=8080
ENV PANDOC_PORT=${PANDOC_PORT}
EXPOSE ${PANDOC_PORT}
CMD ["node", "server.js"]